### ISSUE TITLE
[shelly] Item State 0.00W

### ISSUE THREAD

**Issue by alaub81** [markus7017/myfiles#19]
Hi there,

I think I found a shelly binding bug. I try to explain:

I wondered, that in my influxDB persistence, only, when I restart a shelly Device, or restart the thing, I get a 0 Watt into the database. So I tried to figure out why this is happening and I think I found it. It is because ItemStateUpdatedEvent and ItemStateEvent is getting the last none zero value.
See screenshot attached. 
<img width="545" alt="Bildschirmfoto 2023-11-29 um 16 42 11" src="https://github.com/markus7017/myfiles/assets/5852957/f6162b3c-f467-4c17-a526-fd8caeb05f9f">

Perhaps there is a simple fix for that. My grafana graphs are looking weird without a zero. I am using a persistence rule with at everyUpdate option. Also I do not see any continuous updates, when 0 Watt is on for a long time. But perhaps that's fine.

I hope you will understand the problem. If not, feel free to ask.

cheers
Andreas

**Comment by markus7017** [comment]
I don't het what you are meaning. The binding reads the device data and updates the channel, everything else is not under control of the binding. 
Check events.log to see the updates processed by the framework

**Comment by alaub81** [comment]
Found the problem. persistence configuration was the problem. Updating only every 30s can cause, that the 0 value, which is only published once, is not written to the database.
