### ISSUE TITLE
OH3 not receiving any event updates after changing WiFi

### ISSUE THREAD

**Issue by joeftiger** [markus7017/myfiles#4]
Hello Markus (& Co.?)

My family upgraded from a very old Apple Airport WiFi to a new more powerful ASUS router. 

Ever since then we noticed however, that all shelly items that are battery powered are not updating their sensor data anymore.
For example the Shelly H&T sensors we have are only sending smth. when we press the button on them. 
We changed places to hotter / colder regions, where the webpage of the shellys are showing new sensor data like higher temperatures.
OpenHab however, does not receive thoses changes. 

The shelly configuration has stayed the same since the old WiFi. 
When switching to the Apple WiFi, everything works, when going to the new ASUS router, no updates get through. 

I went through all the settings I could find on the new router and did not find anything weird, especially since the rest of the OH things are working fine. 
Only the battery-powered Shelly sensors stopped sending Updates. 

I manually installed your 3.1.0-SNAPSHOT binding with the appropriate dependencies to test whether the dev version works: No luck. 
The behaviour stays the same and I am quite a bit at a loss. 

Thank you for your help.

**Comment by joeftiger** [comment]
It seems to work now, as OH receives updates from those shellys. 

It's a bit weird, maybe it needed some time to properly get into gear?
This doesn't really make any sense though programmatically. 

Anyway, it's working right now, so I'll close this issue.

**Comment by markus7017** [comment]
good to know that’s now working, may tge Shelly still remembered to old AP and it took a while.

Please post further comments here: https://community.openhab.org/t/shelly-binding/56862/2109
